name: Build

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - main

jobs:
  build-containers:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build containers
      run: docker compose build
